import { useEffect, useRef, useState } from 'react';
import { io, type Socket } from 'socket.io-client';
import { Copy, Mic, MicOff, PhoneOff, Video, VideoOff, Users } from 'lucide-react';
import { getToken } from '@/lib/api';

const WS_URL=(import.meta.env.VITE_API_BASE as string|undefined)?.replace(/\/api\/?$/,'')??window.location.origin;
type PeerView={peerId:string;stream:MediaStream};
type JoinAck={ok:boolean;roomId:string;peerId:string;peers:Array<{peerId:string;email:string}>;error?:string};

export default function VideoConference(){const[roomId,setRoomId]=useState(()=>new URLSearchParams(location.search).get('room')||crypto.randomUUID().slice(0,8));const[joined,setJoined]=useState(false);const[muted,setMuted]=useState(false);const[cameraOff,setCameraOff]=useState(false);const[error,setError]=useState('');const[peers,setPeers]=useState<PeerView[]>([]);const localVideo=useRef<HTMLVideoElement>(null);const localStream=useRef<MediaStream|null>(null);const socketRef=useRef<Socket|null>(null);const pcs=useRef(new Map<string,RTCPeerConnection>());
  const updateRemote=(peerId:string,stream:MediaStream)=>setPeers(v=>[...v.filter(p=>p.peerId!==peerId),{peerId,stream}]);
  const closePeer=(peerId:string)=>{pcs.current.get(peerId)?.close();pcs.current.delete(peerId);setPeers(v=>v.filter(p=>p.peerId!==peerId));};
  const makePeer=(peerId:string,socket:Socket)=>{const existing=pcs.current.get(peerId);if(existing)return existing;const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pcs.current.set(peerId,pc);localStream.current?.getTracks().forEach(track=>pc.addTrack(track,localStream.current!));pc.ontrack=e=>{const stream=e.streams[0]??new MediaStream([e.track]);updateRemote(peerId,stream);};pc.onicecandidate=e=>{if(e.candidate)socket.emit('rtc:ice',{roomId,to:peerId,candidate:e.candidate.toJSON()});};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState))closePeer(peerId);};return pc;};
  const createOffer=async(peerId:string,socket:Socket)=>{const pc=makePeer(peerId,socket);const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('rtc:offer',{roomId,to:peerId,description:offer});};
  const leave=()=>{socketRef.current?.emit('rtc:leave',{roomId});socketRef.current?.disconnect();socketRef.current=null;pcs.current.forEach(pc=>pc.close());pcs.current.clear();localStream.current?.getTracks().forEach(t=>t.stop());localStream.current=null;setPeers([]);setJoined(false);};
  useEffect(()=>()=>leave(),[]);
  const join=async()=>{setError('');const clean=roomId.trim().replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);if(!clean){setError('Enter a meeting room.');return;}setRoomId(clean);try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});localStream.current=stream;if(localVideo.current)localVideo.current.srcObject=stream;const socket=io(`${WS_URL}/chat`,{transports:['websocket'],auth:{token:getToken()||''}});socketRef.current=socket;socket.on('connect_error',e=>setError(e.message));socket.on('rtc:peer-joined',({peerId}:{peerId:string})=>{void createOffer(peerId,socket);});socket.on('rtc:peer-left',({peerId}:{peerId:string})=>closePeer(peerId));socket.on('rtc:offer',async({from,description}:{from:string;description:RTCSessionDescriptionInit})=>{const pc=makePeer(from,socket);await pc.setRemoteDescription(description);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('rtc:answer',{roomId:clean,to:from,description:answer});});socket.on('rtc:answer',async({from,description}:{from:string;description:RTCSessionDescriptionInit})=>{const pc=pcs.current.get(from);if(pc)await pc.setRemoteDescription(description);});socket.on('rtc:ice',async({from,candidate}:{from:string;candidate:RTCIceCandidateInit})=>{const pc=makePeer(from,socket);try{await pc.addIceCandidate(candidate);}catch{}});await new Promise<void>((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Meeting signaling timed out.')),8000);socket.emit('rtc:join',{roomId:clean},(ack:JoinAck)=>{clearTimeout(timeout);if(!ack?.ok)reject(new Error(ack?.error||'Could not join room.'));else{ack.peers.forEach(p=>void createOffer(p.peerId,socket));resolve();}});});setJoined(true);const url=new URL(location.href);url.searchParams.set('room',clean);history.replaceState({},'',url);}catch(e){localStream.current?.getTracks().forEach(t=>t.stop());socketRef.current?.disconnect();setError((e as Error).message||'Camera/microphone access is required.');}};
  const toggleMic=()=>{const next=!muted;localStream.current?.getAudioTracks().forEach(t=>t.enabled=!next);setMuted(next);};const toggleCam=()=>{const next=!cameraOff;localStream.current?.getVideoTracks().forEach(t=>t.enabled=!next);setCameraOff(next);};const copy=()=>navigator.clipboard?.writeText(`${location.origin}${location.pathname}?room=${encodeURIComponent(roomId)}`);
  return <div className="h-full min-h-0 flex flex-col bg-[#07111f] text-white overflow-hidden"><header className="h-16 shrink-0 px-4 border-b border-white/10 flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-cyan-500/15 text-cyan-300 grid place-items-center"><Video className="h-5 w-5"/></div><div><h1 className="font-black">Kobe Meet</h1><p className="text-[11px] text-slate-500">Authenticated peer-to-peer WebRTC meetings</p></div>{joined&&<><span className="ml-auto text-xs text-slate-400">Room <b className="text-white">{roomId}</b></span><button onClick={copy} className="h-9 w-9 rounded-lg border border-white/10 grid place-items-center"><Copy className="h-4 w-4"/></button></>}</header>{!joined?<main className="flex-1 grid place-items-center p-6"><div className="w-full max-w-lg rounded-3xl border border-white/10 bg-white/[0.04] p-6"><Users className="h-10 w-10 text-cyan-300"/><h2 className="text-2xl font-black mt-4">Start or join a meeting</h2><p className="text-sm text-slate-400 mt-2">Everyone joins the same room code while signed into KobeOS. Video and audio travel directly between participants.</p><label className="grid gap-1 text-xs text-slate-400 mt-5">Room code<input value={roomId} onChange={e=>setRoomId(e.target.value)} className="h-11 rounded-xl bg-black/30 border border-white/10 px-3 text-base font-mono"/></label>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}<button onClick={()=>void join()} className="mt-5 w-full h-11 rounded-xl bg-cyan-500 text-[#07111f] font-black">Join meeting</button></div></main>:<><main className="flex-1 min-h-0 overflow-auto p-4"><div className={`grid gap-3 ${peers.length?'sm:grid-cols-2 xl:grid-cols-3':'grid-cols-1 max-w-4xl mx-auto'}`}><VideoTile label="You" stream={localStream.current} videoRef={localVideo} muted/><>{peers.map(p=><VideoTile key={p.peerId} label={`Participant ${p.peerId.slice(0,5)}`} stream={p.stream}/>)}</>{!peers.length&&<div className="rounded-2xl border border-dashed border-white/10 min-h-40 grid place-items-center text-center p-6 text-slate-500"><div><Users className="h-8 w-8 mx-auto mb-2"/><p>Waiting for another participant.</p><button onClick={copy} className="mt-2 text-cyan-300 text-sm underline">Copy invite link</button></div></div>}</div>{error&&<p className="mt-3 text-sm text-rose-300">{error}</p>}</main><footer className="h-20 shrink-0 border-t border-white/10 flex items-center justify-center gap-3"><button onClick={toggleMic} className={`control ${muted?'bg-rose-500/20 text-rose-300':'bg-white/10'}`}>{muted?<MicOff/>:<Mic/>}</button><button onClick={toggleCam} className={`control ${cameraOff?'bg-rose-500/20 text-rose-300':'bg-white/10'}`}>{cameraOff?<VideoOff/>:<Video/>}</button><button onClick={leave} className="h-12 px-5 rounded-full bg-rose-600 font-black inline-flex items-center gap-2"><PhoneOff className="h-5 w-5"/>Leave</button></footer></>}</div>}
function VideoTile({label,stream,videoRef,muted=false}:{label:string;stream:MediaStream|null;videoRef?:React.RefObject<HTMLVideoElement|null>;muted?:boolean}){const ref=useRef<HTMLVideoElement>(null);useEffect(()=>{const node=videoRef?.current??ref.current;if(node&&stream)node.srcObject=stream;},[stream,videoRef]);return <div className="relative aspect-video rounded-2xl overflow-hidden bg-black border border-white/10"><video ref={videoRef??ref} autoPlay playsInline muted={muted} className="w-full h-full object-cover"/><span className="absolute left-3 bottom-3 rounded-lg bg-black/60 px-2 py-1 text-xs font-bold">{label}</span></div>}
