import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1778670115718 implements MigrationInterface {
    name = 'InitialSchema1778670115718'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "warehouse_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "sku" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL DEFAULT '', "unit" character varying NOT NULL DEFAULT 'pcs', "quantity" integer NOT NULL DEFAULT '0', "reorderLevel" integer NOT NULL DEFAULT '0', "location" character varying, "unitCost" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_3c78531abd8b53bb85c3b599e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ea1b2286635f2a596388da358d" ON "warehouse_items" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99914af00d197c51c59bba21a9" ON "warehouse_items" ("sku") `);
        await queryRunner.query(`CREATE TABLE "warehouse_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "itemId" uuid NOT NULL, "type" character varying NOT NULL, "quantity" integer NOT NULL, "reference" character varying, "note" character varying, CONSTRAINT "PK_04d69043bccdb32730f4192fd20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5530d94d6b97f0e7cc52b488db" ON "warehouse_movements" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f753460d944eb6fb94391344e" ON "warehouse_movements" ("itemId") `);
        await queryRunner.query(`CREATE TABLE "properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "address" character varying NOT NULL DEFAULT '', "type" character varying NOT NULL DEFAULT 'residential', "totalUnits" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_2d83bfa0b9fcd45dee1785af44d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_47b8bfd9c3165b8a53cd0c58df" ON "properties" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "property_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "propertyId" uuid NOT NULL, "unitNumber" character varying NOT NULL, "rentAmount" double precision NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'TZS', "status" character varying NOT NULL DEFAULT 'vacant', CONSTRAINT "PK_c7d7d8f633643123e9f9e0a0c83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4031d2e5df66f44fb000a874b0" ON "property_units" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e3f071b6c5b3c50e712534be" ON "property_units" ("propertyId") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "unitId" uuid, "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying, "leaseStart" date, "leaseEnd" date, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dccf2382a3ffe4edfc09b8eeb0" ON "tenants" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_05950ee1c47747d7e054d87c74" ON "tenants" ("unitId") `);
        await queryRunner.query(`CREATE TABLE "rent_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "tenantId" uuid NOT NULL, "unitId" uuid NOT NULL, "amount" double precision NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "forMonth" date NOT NULL, "paidAt" TIMESTAMP WITH TIME ZONE NOT NULL, "method" character varying NOT NULL DEFAULT 'CASH', "reference" character varying, CONSTRAINT "PK_deca3deaaf83de65c31d5efe8a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cad2c54493f3094a17ce18ecda" ON "rent_payments" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ca3bc6f27c3bc26f6e17a34bc" ON "rent_payments" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_396915e6eccad998a8cb728adb" ON "rent_payments" ("unitId") `);
        await queryRunner.query(`CREATE TABLE "todo_lists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "color" character varying NOT NULL DEFAULT '#3b82f6', CONSTRAINT "PK_abf14b565d762fb594a74fe6d71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0aa23dfb514c3bbc7297506da" ON "todo_lists" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "todo_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "listId" uuid NOT NULL, "text" character varying NOT NULL, "done" boolean NOT NULL DEFAULT false, "priority" character varying NOT NULL DEFAULT 'normal', "dueAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7ad331e73b03da55c148c2b5595" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd4c1de9185f44ffe1638e9db0" ON "todo_items" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0be8728f7990ebf8cc627f722f" ON "todo_items" ("listId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "displayName" character varying NOT NULL DEFAULT '', "avatarUrl" character varying, "role" character varying NOT NULL DEFAULT 'user', CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "pos_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "sku" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying NOT NULL DEFAULT '', "price" double precision NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "stock" integer NOT NULL DEFAULT '0', "imageUrl" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_30a78448a7b8e3971b44468f967" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_24cd4069c88b930457771c2bcb" ON "pos_products" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "pos_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "orderNumber" character varying NOT NULL, "subtotal" double precision NOT NULL DEFAULT '0', "taxAmount" double precision NOT NULL DEFAULT '0', "discountAmount" double precision NOT NULL DEFAULT '0', "total" double precision NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'TZS', "status" character varying NOT NULL DEFAULT 'PENDING', "paymentMethod" character varying NOT NULL DEFAULT 'CASH', "customerName" character varying, "customerPhone" character varying, CONSTRAINT "PK_fe63b2bc474b2dc257089d09485" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f6abc0af1c9bb8afb43eeac201" ON "pos_orders" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a877ce211f4dbeffe9cf15420" ON "pos_orders" ("orderNumber") `);
        await queryRunner.query(`CREATE TABLE "pos_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "orderId" uuid NOT NULL, "productId" uuid NOT NULL, "productName" character varying NOT NULL, "unitPrice" double precision NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "lineTotal" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_ad5bd3899fd281de4614a89f629" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_faa090a4a24267e8a53af5e80c" ON "pos_order_items" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_abe045f833394060d870e6bf81" ON "pos_order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7fae11fc7503592827c1489cf" ON "pos_order_items" ("productId") `);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "balance" double precision NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_342cecf691b0d12172e69b2b8f" ON "wallets" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "walletId" uuid NOT NULL, "type" character varying NOT NULL, "amount" double precision NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "status" character varying NOT NULL DEFAULT 'PENDING', "counterparty" character varying, "reference" character varying, "description" character varying NOT NULL DEFAULT '', CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db3d5427524a0b8f16c5f839c1" ON "payment_transactions" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eabc13cb2c6d3d93499a29951" ON "payment_transactions" ("walletId") `);
        await queryRunner.query(`CREATE TABLE "credit_loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "principal" double precision NOT NULL, "currency" character varying NOT NULL DEFAULT 'TZS', "interestRate" double precision NOT NULL DEFAULT '0', "termMonths" integer NOT NULL DEFAULT '12', "outstanding" double precision NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'ACTIVE', "disbursedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_fe2ceaf53cb0211d68ae193a7f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a24a000fe431d8cd62637fe9e" ON "credit_loans" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "title" character varying NOT NULL DEFAULT '', "body" text NOT NULL DEFAULT '', "tags" text NOT NULL DEFAULT '', "pinned" boolean NOT NULL DEFAULT false, "color" character varying NOT NULL DEFAULT '#fde68a', CONSTRAINT "PK_af6206538ea96c4e77e9f400c3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8fcc29811c424b531ac9a341d2" ON "notes" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "password_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "title" character varying NOT NULL, "url" character varying, "username" character varying, "cipher" text NOT NULL, "category" character varying NOT NULL DEFAULT '', "favorite" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6b64c65c17a03eec1b1661c85cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cbf9873e990cadade7b4e8297b" ON "password_entries" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "media_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "kind" character varying NOT NULL, "name" character varying NOT NULL, "mimeType" character varying, "src" character varying NOT NULL, "duration" integer NOT NULL DEFAULT '0', "size" integer NOT NULL DEFAULT '0', "metadata" text, CONSTRAINT "PK_ca47e9f67a5e5d8af1e75d66ee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fe13ab28c04fb5c91be1fc6958" ON "media_assets" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "playlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "trackIds" text NOT NULL DEFAULT '', CONSTRAINT "PK_a4597f4189a75d20507f3f7ef0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa5d498a2f045be2fb71ef98d4" ON "playlists" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "kanban_boards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_84d66b74a73923e66911210a460" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c68f7fbcff9c9bca5fe850927" ON "kanban_boards" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "kanban_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "boardId" uuid NOT NULL, "title" character varying NOT NULL, "position" integer NOT NULL DEFAULT '0', "color" character varying NOT NULL DEFAULT '#64748b', CONSTRAINT "PK_502614605b052be980fc3cd3836" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a81f03f2897c3acb40450a3b18" ON "kanban_columns" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e65167585769407d9fcfb0028" ON "kanban_columns" ("boardId") `);
        await queryRunner.query(`CREATE TABLE "kanban_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "columnId" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL DEFAULT '', "position" integer NOT NULL DEFAULT '0', "labels" text NOT NULL DEFAULT '', "priority" character varying NOT NULL DEFAULT 'medium', "colorTag" character varying, "dueAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_06b994c79a20b9e7d5203dce4b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0476a085b63dfc8d0c61c3ca18" ON "kanban_cards" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e4c557a3547225d39885fce5a7" ON "kanban_cards" ("columnId") `);
        await queryRunner.query(`CREATE TABLE "hotel_rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "roomNumber" character varying NOT NULL, "type" character varying NOT NULL, "rate" double precision NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'TZS', "capacity" integer NOT NULL DEFAULT '2', "status" character varying NOT NULL DEFAULT 'available', CONSTRAINT "PK_1d226a170f53beff6c64f10c3ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1193dc5a5b236ce426d521a1f8" ON "hotel_rooms" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e26c201283ba564d83060e4f75" ON "hotel_rooms" ("roomNumber") `);
        await queryRunner.query(`CREATE TABLE "hotel_guests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying, "nationality" character varying, "idType" character varying, "idNumber" character varying, CONSTRAINT "PK_f63b6b5b865f635503426312f0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6678953b9a9fa52505aa471bf" ON "hotel_guests" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "hotel_bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "roomId" uuid NOT NULL, "guestId" uuid NOT NULL, "checkIn" date NOT NULL, "checkOut" date NOT NULL, "guestCount" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'CONFIRMED', "totalAmount" double precision NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'TZS', CONSTRAINT "PK_33689dfe5dcc235cca4e6b24549" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b97dea0dbb0961b5dfc4ef4f7f" ON "hotel_bookings" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_224845d491b2bdfe1d636dfc0b" ON "hotel_bookings" ("roomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a60639c8faa2798118dfa3e96" ON "hotel_bookings" ("guestId") `);
        await queryRunner.query(`CREATE TABLE "vfs_nodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "path" character varying NOT NULL, "parentPath" character varying, "name" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'file', "mimeType" character varying, "size" integer NOT NULL DEFAULT '0', "content" text, "contentBinary" bytea, CONSTRAINT "uq_vfs_owner_path" UNIQUE ("ownerId", "path"), CONSTRAINT "PK_f0b3e68a5eb3d6bc6bbc348a8a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64ce776774681bb91400cee641" ON "vfs_nodes" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c4cdfed836cb1c68f1998dbae" ON "vfs_nodes" ("path") `);
        await queryRunner.query(`CREATE INDEX "IDX_ada14795cfeb8da8893538fc55" ON "vfs_nodes" ("parentPath") `);
        await queryRunner.query(`CREATE TABLE "emails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "folder" character varying NOT NULL DEFAULT 'inbox', "fromAddress" character varying NOT NULL, "fromName" character varying NOT NULL DEFAULT '', "toAddresses" text NOT NULL, "ccAddresses" text NOT NULL DEFAULT '', "subject" character varying NOT NULL DEFAULT '', "body" text NOT NULL DEFAULT '', "read" boolean NOT NULL DEFAULT false, "starred" boolean NOT NULL DEFAULT false, "labels" text NOT NULL DEFAULT '', CONSTRAINT "PK_a54dcebef8d05dca7e839749571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce60daf5817725cbb20131e0df" ON "emails" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_15302da9327061f6b007a38f38" ON "emails" ("folder") `);
        await queryRunner.query(`CREATE TABLE "discount_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "value" double precision NOT NULL, "productScope" character varying NOT NULL DEFAULT 'All', "customerScope" character varying NOT NULL DEFAULT 'All', "startDate" TIMESTAMP WITH TIME ZONE, "endDate" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'Active', CONSTRAINT "PK_8f540f64aa8a5ab9d3996f01225" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3a0196657a9e77b8da09c8a557" ON "discount_rules" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "code" character varying NOT NULL, "type" character varying NOT NULL, "value" double precision NOT NULL, "usageLimit" integer NOT NULL DEFAULT '0', "usageCount" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP WITH TIME ZONE, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1bff6cfe74ac8eed1ebebc877e" ON "coupons" ("ownerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "endDate" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'Scheduled', "budget" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90d64375279aec38e309f12ff7" ON "campaigns" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "creators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "handle" character varying NOT NULL, "niche" character varying NOT NULL DEFAULT '', "followers" integer NOT NULL DEFAULT '0', "engagement" double precision NOT NULL DEFAULT '0', "avatarUrl" character varying, "contactEmail" character varying, "platforms" text NOT NULL DEFAULT '', "verified" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b27dd693f7df17bbfc21f00166a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05d03c41506b2c21d01cfa93d7" ON "creators" ("ownerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dec6d0c8c47e2c4540654bf919" ON "creators" ("handle") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying, "phone" character varying, "company" character varying, "jobTitle" character varying, "address" character varying, "groups" text NOT NULL DEFAULT '', "favorite" boolean NOT NULL DEFAULT false, "notes" text NOT NULL DEFAULT '', "color" character varying NOT NULL DEFAULT '#3b82f6', CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_270a85b7f2d4b6821dc7642e6a" ON "contacts" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "chat_channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "type" character varying NOT NULL DEFAULT 'channel', CONSTRAINT "PK_efecd102855fb96e1428306ec6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c82208b3028038a5994f572eac" ON "chat_channels" ("slug") `);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "channelId" uuid NOT NULL, "senderId" uuid NOT NULL, "senderName" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'message', "text" text NOT NULL, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a22356d08c23eb68b98c75452" ON "chat_messages" ("channelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc6b58e41e9a871dacbe9077de" ON "chat_messages" ("senderId") `);
        await queryRunner.query(`CREATE TABLE "parcels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "parcelId" character varying NOT NULL, "senderName" character varying NOT NULL, "senderPhone" character varying NOT NULL, "ownerName" character varying NOT NULL, "ownerPhone" character varying NOT NULL, "destination" character varying NOT NULL, "packageCount" integer NOT NULL DEFAULT '1', "weight" double precision NOT NULL DEFAULT '0', "description" character varying NOT NULL DEFAULT '', "paymentMode" character varying NOT NULL DEFAULT 'PAY_NOW', "status" character varying NOT NULL DEFAULT 'REGISTERED', CONSTRAINT "PK_47847f79fee8a3926f2b3022a96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fc4f7eb441e6ca7208d7009e2" ON "parcels" ("ownerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4ef2cd7f486f9cbd3cfefdcf35" ON "parcels" ("parcelId") `);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "shipmentId" character varying NOT NULL, "origin" character varying NOT NULL, "destination" character varying NOT NULL, "weight" double precision NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'PENDING', "etd" TIMESTAMP WITH TIME ZONE, "eta" TIMESTAMP WITH TIME ZONE, "carrier" character varying, "flightNumber" character varying, CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce50e2213d30974373764a8bc3" ON "shipments" ("ownerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b7024576680706ba9df43e18f4" ON "shipments" ("shipmentId") `);
        await queryRunner.query(`CREATE TABLE "cargo_drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "vehicle" character varying, "plateNumber" character varying, "status" character varying NOT NULL DEFAULT 'AVAILABLE', "rating" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_45e734355e4c17a18d87591638e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_434d5f47e842fece3e6459ae78" ON "cargo_drivers" ("ownerId") `);
        await queryRunner.query(`CREATE TABLE "cargo_flights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "flightNumber" character varying NOT NULL, "origin" character varying NOT NULL, "destination" character varying NOT NULL, "departureAt" TIMESTAMP WITH TIME ZONE NOT NULL, "arrivalAt" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'SCHEDULED', "carrier" character varying, "capacityKg" double precision NOT NULL DEFAULT '0', "bookedKg" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_8af81d8db1a7c492c4882982094" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_863d298575bef0f2bf9aded4b5" ON "cargo_flights" ("ownerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_00c4e7383ae0cd28d46262932e" ON "cargo_flights" ("flightNumber") `);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ownerId" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL DEFAULT '', "startAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endAt" TIMESTAMP WITH TIME ZONE NOT NULL, "allDay" boolean NOT NULL DEFAULT false, "color" character varying NOT NULL DEFAULT '#3b82f6', "location" character varying, CONSTRAINT "PK_faf5391d232322a87cdd1c6f30c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bbec7b87030771f168cf6625d5" ON "calendar_events" ("ownerId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_bbec7b87030771f168cf6625d5"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00c4e7383ae0cd28d46262932e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_863d298575bef0f2bf9aded4b5"`);
        await queryRunner.query(`DROP TABLE "cargo_flights"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_434d5f47e842fece3e6459ae78"`);
        await queryRunner.query(`DROP TABLE "cargo_drivers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7024576680706ba9df43e18f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce50e2213d30974373764a8bc3"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ef2cd7f486f9cbd3cfefdcf35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fc4f7eb441e6ca7208d7009e2"`);
        await queryRunner.query(`DROP TABLE "parcels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc6b58e41e9a871dacbe9077de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a22356d08c23eb68b98c75452"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c82208b3028038a5994f572eac"`);
        await queryRunner.query(`DROP TABLE "chat_channels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_270a85b7f2d4b6821dc7642e6a"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dec6d0c8c47e2c4540654bf919"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05d03c41506b2c21d01cfa93d7"`);
        await queryRunner.query(`DROP TABLE "creators"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90d64375279aec38e309f12ff7"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bff6cfe74ac8eed1ebebc877e"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a0196657a9e77b8da09c8a557"`);
        await queryRunner.query(`DROP TABLE "discount_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15302da9327061f6b007a38f38"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce60daf5817725cbb20131e0df"`);
        await queryRunner.query(`DROP TABLE "emails"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ada14795cfeb8da8893538fc55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c4cdfed836cb1c68f1998dbae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64ce776774681bb91400cee641"`);
        await queryRunner.query(`DROP TABLE "vfs_nodes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a60639c8faa2798118dfa3e96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_224845d491b2bdfe1d636dfc0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b97dea0dbb0961b5dfc4ef4f7f"`);
        await queryRunner.query(`DROP TABLE "hotel_bookings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6678953b9a9fa52505aa471bf"`);
        await queryRunner.query(`DROP TABLE "hotel_guests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e26c201283ba564d83060e4f75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1193dc5a5b236ce426d521a1f8"`);
        await queryRunner.query(`DROP TABLE "hotel_rooms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4c557a3547225d39885fce5a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0476a085b63dfc8d0c61c3ca18"`);
        await queryRunner.query(`DROP TABLE "kanban_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e65167585769407d9fcfb0028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a81f03f2897c3acb40450a3b18"`);
        await queryRunner.query(`DROP TABLE "kanban_columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c68f7fbcff9c9bca5fe850927"`);
        await queryRunner.query(`DROP TABLE "kanban_boards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa5d498a2f045be2fb71ef98d4"`);
        await queryRunner.query(`DROP TABLE "playlists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe13ab28c04fb5c91be1fc6958"`);
        await queryRunner.query(`DROP TABLE "media_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbf9873e990cadade7b4e8297b"`);
        await queryRunner.query(`DROP TABLE "password_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fcc29811c424b531ac9a341d2"`);
        await queryRunner.query(`DROP TABLE "notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a24a000fe431d8cd62637fe9e"`);
        await queryRunner.query(`DROP TABLE "credit_loans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eabc13cb2c6d3d93499a29951"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db3d5427524a0b8f16c5f839c1"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_342cecf691b0d12172e69b2b8f"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7fae11fc7503592827c1489cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abe045f833394060d870e6bf81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faa090a4a24267e8a53af5e80c"`);
        await queryRunner.query(`DROP TABLE "pos_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a877ce211f4dbeffe9cf15420"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6abc0af1c9bb8afb43eeac201"`);
        await queryRunner.query(`DROP TABLE "pos_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24cd4069c88b930457771c2bcb"`);
        await queryRunner.query(`DROP TABLE "pos_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0be8728f7990ebf8cc627f722f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd4c1de9185f44ffe1638e9db0"`);
        await queryRunner.query(`DROP TABLE "todo_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0aa23dfb514c3bbc7297506da"`);
        await queryRunner.query(`DROP TABLE "todo_lists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_396915e6eccad998a8cb728adb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ca3bc6f27c3bc26f6e17a34bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cad2c54493f3094a17ce18ecda"`);
        await queryRunner.query(`DROP TABLE "rent_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05950ee1c47747d7e054d87c74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dccf2382a3ffe4edfc09b8eeb0"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e3f071b6c5b3c50e712534be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4031d2e5df66f44fb000a874b0"`);
        await queryRunner.query(`DROP TABLE "property_units"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47b8bfd9c3165b8a53cd0c58df"`);
        await queryRunner.query(`DROP TABLE "properties"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f753460d944eb6fb94391344e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5530d94d6b97f0e7cc52b488db"`);
        await queryRunner.query(`DROP TABLE "warehouse_movements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99914af00d197c51c59bba21a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1b2286635f2a596388da358d"`);
        await queryRunner.query(`DROP TABLE "warehouse_items"`);
    }

}
