import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Banknote, Boxes, Calculator, Check, Coins, FileText, Plus, Receipt, ShieldCheck, Trash2, Users } from 'lucide-react';

type Department = 'bar' | 'kitchen' | 'cleaning' | 'room-amenities';
interface RequestLine { inventoryId?: string; name: string; quantity: number; approvedQuantity?: number; unit: string; unitCost?: number; totalCost?: number }
interface Request { id: string; department: Department; lines: RequestLine[]; status: string; currency: string; createdAt: string; note?: string }
interface Payroll { id: string; employeeName: string; period: string; baseSalary: number; overtime: number; allowances: number; deductions: number; netPay: number; status: string; currency: string }
interface Petty { id: string; kind: string; category: string; amount: number; description: string; entryDate: string; currency: string }
interface Asset { id: string; assetCode: string; name: string; category: string; acquisitionDate: string; acquisitionCost: number; residualValue: number; usefulLifeMonths: number; currency: string }
interface Statements { revenue: Array<{ account: string; amount: number }>; expenses: Array<{ account: string; amount: number }>; totalRevenue: number; totalExpenses: number; netProfit: number; fixedAssetsNet: number; ledgerCount: number }

const fmt = (n: number, currency = 'TZS') => `${currency} ${Math.round(Number(n) || 0).toLocaleString()}`;
const deptLabel: Record<Department, string> = { bar: 'Bar', kitchen: 'Kitchen', cleaning: 'Cleaning', 'room-amenities': 'Room amenities' };
const input = 'w-full h-10 rounded-lg border border-white/10 bg-black/10 px-3 text-sm outline-none focus:border-indigo-400';

export default function HotelOperationsBoard({ darkMode }: { darkMode: boolean }) {
  const [tab, setTab] = useState<'statements' | 'requests' | 'payroll' | 'petty' | 'assets'>('statements');
  const [requests, setRequests] = useState<Request[]>([]); const [payroll, setPayroll] = useState<Payroll[]>([]); const [petty, setPetty] = useState<Petty[]>([]); const [assets, setAssets] = useState<Asset[]>([]); const [statement, setStatement] = useState<Statements | null>(null); const [error, setError] = useState<string | null>(null);
  const [payrollForm, setPayrollForm] = useState({ employeeName: '', period: new Date().toISOString().slice(0, 7), baseSalary: '', overtime: '0', allowances: '0', deductions: '0' });
  const [pettyForm, setPettyForm] = useState({ category: 'general', amount: '', description: '', paidTo: '', entryDate: new Date().toISOString().slice(0, 10) });
  const [assetForm, setAssetForm] = useState({ name: '', category: 'hotel equipment', acquisitionDate: new Date().toISOString().slice(0, 10), acquisitionCost: '', residualValue: '0', usefulLifeMonths: '60' });
  const surface = darkMode ? 'bg-[#13131f] border-white/[0.06]' : 'bg-white border-gray-200';

  const load = async () => { try { const [r, p, c, a, s] = await Promise.all([api<Request[]>('/hotel/operations/requisitions'), api<Payroll[]>('/hotel/operations/payroll'), api<Petty[]>('/hotel/operations/petty-cash'), api<Asset[]>('/hotel/operations/assets'), api<Statements>('/hotel/operations/statements')]); setRequests(r ?? []); setPayroll(p ?? []); setPetty(c ?? []); setAssets(a ?? []); setStatement(s); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  const pending = requests.filter((r) => r.status === 'PENDING').length;
  const monthlyDep = useMemo(() => assets.reduce((s, a) => s + Math.max(0, (Number(a.acquisitionCost) - Number(a.residualValue)) / Math.max(1, a.usefulLifeMonths)), 0), [assets]);

  const review = async (request: Request) => { try { const lines = request.lines.map((line) => ({ ...line, approvedQuantity: line.approvedQuantity ?? line.quantity, unitCost: Number(line.unitCost) || 0 })); const updated = await api<Request>(`/hotel/operations/requisitions/${request.id}/review`, { method: 'PATCH', body: JSON.stringify({ lines }) }); setRequests((rows) => rows.map((row) => row.id === updated.id ? updated : row)); } catch (e) { setError((e as Error).message); } };
  const purchase = async (request: Request) => { try { await api(`/hotel/operations/requisitions/${request.id}/purchase`, { method: 'POST' }); await load(); } catch (e) { setError((e as Error).message); } };
  const createPayroll = async () => { try { await api('/hotel/operations/payroll', { method: 'POST', body: JSON.stringify({ ...payrollForm, baseSalary: Number(payrollForm.baseSalary), overtime: Number(payrollForm.overtime), allowances: Number(payrollForm.allowances), deductions: Number(payrollForm.deductions) }) }); setPayrollForm({ employeeName: '', period: new Date().toISOString().slice(0, 7), baseSalary: '', overtime: '0', allowances: '0', deductions: '0' }); await load(); } catch (e) { setError((e as Error).message); } };
  const createPetty = async () => { try { await api('/hotel/operations/petty-cash', { method: 'POST', body: JSON.stringify({ ...pettyForm, kind: 'expense', amount: Number(pettyForm.amount) }) }); setPettyForm({ category: 'general', amount: '', description: '', paidTo: '', entryDate: new Date().toISOString().slice(0, 10) }); await load(); } catch (e) { setError((e as Error).message); } };
  const createAsset = async () => { try { await api('/hotel/operations/assets', { method: 'POST', body: JSON.stringify({ ...assetForm, acquisitionCost: Number(assetForm.acquisitionCost), residualValue: Number(assetForm.residualValue), usefulLifeMonths: Number(assetForm.usefulLifeMonths) }) }); setAssetForm({ name: '', category: 'hotel equipment', acquisitionDate: new Date().toISOString().slice(0, 10), acquisitionCost: '', residualValue: '0', usefulLifeMonths: '60' }); await load(); } catch (e) { setError((e as Error).message); } };

  const nav = [{ id: 'statements', label: 'Statements', icon: Calculator }, { id: 'requests', label: `Requests${pending ? ` (${pending})` : ''}`, icon: ClipboardIcon }, { id: 'payroll', label: 'HR & Payroll', icon: Users }, { id: 'petty', label: 'Petty cash', icon: Coins }, { id: 'assets', label: 'Assets', icon: Boxes }] as const;
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Hotel operations & accounting</h1><p className={darkMode ? 'text-sm text-gray-400' : 'text-sm text-gray-500'}>USALI-style departmental controls connected to inventory and the general ledger</p></div><div className="flex gap-2 flex-wrap">{nav.map(({ id, label, icon: Icon }) => <Button key={id} size="sm" variant={tab === id ? 'default' : 'outline'} className={tab === id ? 'bg-indigo-600' : darkMode ? 'border-white/10' : ''} onClick={() => setTab(id)}><Icon className="w-3.5 h-3.5 mr-1" />{label}</Button>)}</div></div>{error && <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-300">{error}<button className="float-right" onClick={() => setError(null)}>×</button></div>}
    {tab === 'statements' && <div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Revenue', statement?.totalRevenue ?? 0, 'text-emerald-400'], ['Expenses', statement?.totalExpenses ?? 0, 'text-rose-400'], ['Net profit', statement?.netProfit ?? 0, 'text-cyan-400'], ['Assets net', statement?.fixedAssetsNet ?? 0, 'text-violet-400']].map(([label, value, tone]) => <Card key={String(label)} className={surface}><CardContent className="p-4"><div className={`text-xl font-extrabold ${tone}`}>{fmt(Number(value))}</div><div className="text-xs text-gray-400">{label}</div></CardContent></Card>)}</div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Card className={surface}><CardContent className="p-4"><h3 className="font-semibold mb-3">Revenue by department</h3>{(statement?.revenue ?? []).map((row) => <div key={row.account} className="flex justify-between border-b border-white/5 py-2 text-sm"><span>{row.account}</span><span className="text-emerald-400 font-bold">{fmt(row.amount)}</span></div>)}</CardContent></Card><Card className={surface}><CardContent className="p-4"><h3 className="font-semibold mb-3">Expense & depreciation</h3>{(statement?.expenses ?? []).map((row) => <div key={row.account} className="flex justify-between border-b border-white/5 py-2 text-sm"><span>{row.account}</span><span className="text-rose-400 font-bold">{fmt(row.amount)}</span></div>)}<p className="text-[11px] text-gray-500 mt-3">Monthly straight-line depreciation: {fmt(monthlyDep)}</p></CardContent></Card></div></div>}
    {tab === 'requests' && <Card className={surface}><CardContent className="p-4 space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Department requests</h3><span className="text-xs text-gray-400">Edit approved quantity and unit price before purchase</span></div>{requests.length === 0 ? <p className="text-sm text-gray-500 py-6">No department requests yet.</p> : requests.map((request) => <RequestCard key={request.id} request={request} onReview={review} onPurchase={purchase} darkMode={darkMode} />)}</CardContent></Card>}
    {tab === 'payroll' && <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card className={surface}><CardContent className="p-4 space-y-2"><h3 className="font-semibold flex items-center gap-2"><Plus className="w-4 h-4" />Post salary</h3><input className={input} placeholder="Employee name" value={payrollForm.employeeName} onChange={(e) => setPayrollForm({ ...payrollForm, employeeName: e.target.value })} /><input className={input} placeholder="Period e.g. 2026-08" value={payrollForm.period} onChange={(e) => setPayrollForm({ ...payrollForm, period: e.target.value })} /><input className={input} type="number" placeholder="Base salary" value={payrollForm.baseSalary} onChange={(e) => setPayrollForm({ ...payrollForm, baseSalary: e.target.value })} /><div className="grid grid-cols-2 gap-2"><input className={input} type="number" placeholder="Overtime" value={payrollForm.overtime} onChange={(e) => setPayrollForm({ ...payrollForm, overtime: e.target.value })} /><input className={input} type="number" placeholder="Allowances" value={payrollForm.allowances} onChange={(e) => setPayrollForm({ ...payrollForm, allowances: e.target.value })} /></div><input className={input} type="number" placeholder="Deductions" value={payrollForm.deductions} onChange={(e) => setPayrollForm({ ...payrollForm, deductions: e.target.value })} /><Button onClick={() => void createPayroll()} className="w-full bg-indigo-600">Post to payroll</Button></CardContent></Card><Card className={`${surface} lg:col-span-2`}><CardContent className="p-4"><h3 className="font-semibold mb-3">Payroll register</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-xs text-gray-500"><tr><th className="text-left pb-2">Employee</th><th className="text-left pb-2">Period</th><th className="text-right pb-2">Net pay</th><th className="text-right pb-2">Status</th><th /></tr></thead><tbody>{payroll.map((row) => <tr key={row.id} className="border-t border-white/5"><td className="py-2">{row.employeeName}</td><td className="py-2">{row.period}</td><td className="py-2 text-right font-bold">{fmt(row.netPay, row.currency)}</td><td className="py-2 text-right"><Badge variant="outline">{row.status}</Badge></td><td className="py-2 text-right">{row.status === 'POSTED' && <Button size="sm" variant="outline" onClick={async () => { await api(`/hotel/operations/payroll/${row.id}/pay`, { method: 'POST' }); await load(); }}>Pay</Button>}</td></tr>)}</tbody></table></div></CardContent></Card></div>}
    {tab === 'petty' && <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card className={surface}><CardContent className="p-4 space-y-2"><h3 className="font-semibold"><Receipt className="w-4 h-4 inline mr-1" />New petty-cash expense</h3><input className={input} placeholder="Category" value={pettyForm.category} onChange={(e) => setPettyForm({ ...pettyForm, category: e.target.value })} /><input className={input} type="number" placeholder="Amount" value={pettyForm.amount} onChange={(e) => setPettyForm({ ...pettyForm, amount: e.target.value })} /><input className={input} placeholder="Description" value={pettyForm.description} onChange={(e) => setPettyForm({ ...pettyForm, description: e.target.value })} /><input className={input} placeholder="Paid to" value={pettyForm.paidTo} onChange={(e) => setPettyForm({ ...pettyForm, paidTo: e.target.value })} /><input className={input} type="date" value={pettyForm.entryDate} onChange={(e) => setPettyForm({ ...pettyForm, entryDate: e.target.value })} /><Button onClick={() => void createPetty()} className="w-full bg-indigo-600">Record expense</Button></CardContent></Card><Card className={`${surface} lg:col-span-2`}><CardContent className="p-4"><h3 className="font-semibold mb-3">Petty-cash book</h3>{petty.map((row) => <div key={row.id} className="flex justify-between gap-3 border-t border-white/5 py-2 text-sm"><div><div className="font-medium">{row.description}</div><div className="text-xs text-gray-500">{row.entryDate} · {row.category}</div></div><span className="text-rose-400 font-bold">{fmt(row.amount, row.currency)}</span></div>)}</CardContent></Card></div>}
    {tab === 'assets' && <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card className={surface}><CardContent className="p-4 space-y-2"><h3 className="font-semibold"><Boxes className="w-4 h-4 inline mr-1" />Register fixed asset</h3><input className={input} placeholder="Asset name" value={assetForm.name} onChange={(e) => setAssetForm({ ...assetForm, name: e.target.value })} /><input className={input} placeholder="Category" value={assetForm.category} onChange={(e) => setAssetForm({ ...assetForm, category: e.target.value })} /><input className={input} type="date" value={assetForm.acquisitionDate} onChange={(e) => setAssetForm({ ...assetForm, acquisitionDate: e.target.value })} /><input className={input} type="number" placeholder="Acquisition cost" value={assetForm.acquisitionCost} onChange={(e) => setAssetForm({ ...assetForm, acquisitionCost: e.target.value })} /><div className="grid grid-cols-2 gap-2"><input className={input} type="number" placeholder="Residual value" value={assetForm.residualValue} onChange={(e) => setAssetForm({ ...assetForm, residualValue: e.target.value })} /><input className={input} type="number" placeholder="Life (months)" value={assetForm.usefulLifeMonths} onChange={(e) => setAssetForm({ ...assetForm, usefulLifeMonths: e.target.value })} /></div><p className="text-[11px] text-gray-500">Code is generated automatically, e.g. AST-2026-123456.</p><Button onClick={() => void createAsset()} className="w-full bg-indigo-600">Register asset</Button></CardContent></Card><Card className={`${surface} lg:col-span-2`}><CardContent className="p-4"><h3 className="font-semibold mb-3">Fixed-asset register</h3>{assets.map((row) => <div key={row.id} className="flex justify-between gap-3 border-t border-white/5 py-2 text-sm"><div><div className="font-medium">{row.assetCode} · {row.name}</div><div className="text-xs text-gray-500">{row.category} · {row.acquisitionDate} · {row.usefulLifeMonths} months</div></div><span className="text-violet-400 font-bold">{fmt(row.acquisitionCost, row.currency)}</span></div>)}</CardContent></Card></div>}
  </div>;
}

function ClipboardIcon(props: { className?: string }) { return <FileText {...props} />; }
function RequestCard({ request, onReview, onPurchase, darkMode }: { request: Request; onReview: (request: Request) => Promise<void>; onPurchase: (request: Request) => Promise<void>; darkMode: boolean }) {
  const [lines, setLines] = useState(request.lines.map((line) => ({ ...line, approvedQuantity: line.approvedQuantity ?? line.quantity, unitCost: line.unitCost ?? 0 })));
  const total = lines.reduce((s, line) => s + Number(line.approvedQuantity || 0) * Number(line.unitCost || 0), 0);
  return <div className={`rounded-xl border p-3 ${darkMode ? 'border-white/10 bg-white/[0.02]' : 'border-gray-200 bg-gray-50'}`}><div className="flex items-center justify-between gap-2 mb-2"><div className="font-semibold text-sm">{deptLabel[request.department]} · {new Date(request.createdAt).toLocaleDateString()}</div><Badge variant="outline">{request.status}</Badge></div><div className="space-y-2">{lines.map((line, index) => <div key={`${line.name}-${index}`} className="grid grid-cols-[1fr_72px_92px] gap-2 items-center"><span className="text-xs">{line.name} <span className="text-gray-500">({line.quantity} {line.unit})</span></span><input className={input} type="number" min="0" value={line.approvedQuantity} onChange={(e) => setLines((current) => current.map((row, i) => i === index ? { ...row, approvedQuantity: Number(e.target.value) } : row))} /><input className={input} type="number" min="0" placeholder="Unit price" value={line.unitCost} onChange={(e) => setLines((current) => current.map((row, i) => i === index ? { ...row, unitCost: Number(e.target.value) } : row))} /></div>)}</div><div className="flex items-center justify-between gap-2 mt-3"><span className="text-xs text-gray-400">Order total: <b className="text-emerald-400">{fmt(total, request.currency)}</b></span><div className="flex gap-2">{request.status !== 'PURCHASED' && request.status !== 'CANCELLED' && <Button size="sm" variant="outline" onClick={() => void onReview({ ...request, lines })}><Check className="w-3.5 h-3.5 mr-1" />Approve</Button>}{request.status === 'APPROVED' && <Button size="sm" className="bg-emerald-600" onClick={() => void onPurchase(request)}><Receipt className="w-3.5 h-3.5 mr-1" />Update inventory</Button>}</div></div></div>;
}
