import React, { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { ensureSession } from '@/lib/auth';
import { BarChart3, Building2, DoorOpen, Users, FileText, Receipt, Wrench, UserCheck, Settings, Search, RefreshCw, Plus, CreditCard, X, CheckCircle2, Loader2, MapPin, Phone, Mail, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { QRCodeSVG } from 'qrcode.react';

type Tab = 'dashboard' | 'properties' | 'units' | 'tenants' | 'leases' | 'rent' | 'maintenance' | 'vendors' | 'settings';
type Status = 'Active' | 'Pending' | 'Late' | 'Vacant' | 'Occupied' | 'Open' | 'Assigned' | 'In Progress' | 'Completed' | 'Paid' | 'Overdue' | 'Partial' | 'Missing' | 'Future';

interface Property { id: string; name: string; type: string; address: string; units: number; occupied: number; monthlyIncome: number; color: string }
interface Unit { id: string; propertyId: string; number: string; type: string; beds: number; baths: number; sqft: number; rent: number; status: Status; tenantId?: string; tenantName?: string }
interface Tenant { id: string; name: string; phone: string; email: string; propertyId: string; unitId: string; unit: string; leaseStart: string; leaseEnd: string; monthlyRent: number; status: Status; shortCode: string; paid: number; balance: number; employer?: string; emergency?: string }
interface Lease { id: string; tenantId: string; unitId: string; start: string; end: string; rent: number; deposit: number; dueDay: number; lateFee: number; status: Status }
interface Charge { id: string; tenantId: string; unitId: string; period: string; due: string; amount: number; paid: number; status: Status }
interface Vendor { id: string; name: string; category: string; phone: string; email: string }
interface WorkOrder { id: string; propertyId: string; unitId?: string; tenantId?: string; vendorId?: string; title: string; priority: Status; status: Status; cost: number }
interface Payment { id: string; tenantId: string; unitId: string; amount: number; paidAt: string; method: string; reference: string }

interface ApiProperty { id: string; name: string; address: string; type: 'residential' | 'commercial' | 'mixed'; totalUnits: number }
interface ApiUnit { id: string; propertyId: string; unitNumber: string; rentAmount: number; status: 'vacant' | 'occupied' | 'maintenance' }
interface ApiTenant { id: string; unitId?: string | null; name: string; phone: string; email?: string | null; leaseStart?: string | null; leaseEnd?: string | null; status: 'active' | 'past' | 'pending' }
interface ApiPayment { id: string; tenantId: string; unitId: string; amount: number; forMonth: string; paidAt: string; method: string; reference?: string | null }

const y = new Date().getFullYear();
const nowPeriod = `${y}-${String(new Date().getMonth()+1).padStart(2,'0')}`;
const money = (n: number) => `TZS ${Math.round(n || 0).toLocaleString()}`;
const initials = (name: string) => name.split(' ').map((x) => x[0]).join('').slice(0,2).toUpperCase();
const periodName = (p: string) => `${p.split('-')[1]}/${p.split('-')[0]}`;
const shiftPeriod = (p: string, d: number) => { const [yy, mm] = p.split('-').map(Number); const x = new Date(yy, mm - 1 + d, 1); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`; };

const demo = (() => {
  const properties: Property[] = [
    { id:'p1', name:'Mbezi Beach Apartments', type:'Multi-Family', address:'Mbezi Beach, Dar es Salaam', units:24, occupied:20, monthlyIncome:48_000_000, color:'blue' },
    { id:'p2', name:'Masaki Office Complex', type:'Commercial', address:'Masaki, Dar es Salaam', units:12, occupied:10, monthlyIncome:72_000_000, color:'emerald' },
    { id:'p3', name:'Kariakoo Retail Plaza', type:'Commercial', address:'Kariakoo, Dar es Salaam', units:18, occupied:14, monthlyIncome:54_000_000, color:'amber' },
  ];
  const units: Unit[] = [
    { id:'u1', propertyId:'p1', number:'A-12', type:'2 Bedroom', beds:2, baths:1, sqft:850, rent:2_500_000, status:'Occupied', tenantId:'t1', tenantName:'James Mwakasege' },
    { id:'u2', propertyId:'p1', number:'B-05', type:'1 Bedroom', beds:1, baths:1, sqft:550, rent:1_800_000, status:'Occupied', tenantId:'t2', tenantName:'Grace Mwangala' },
    { id:'u3', propertyId:'p1', number:'A-01', type:'3 Bedroom', beds:3, baths:2, sqft:1200, rent:3_500_000, status:'Vacant' },
    { id:'u4', propertyId:'p2', number:'Suite-301', type:'Office', beds:0, baths:2, sqft:1500, rent:6_000_000, status:'Occupied', tenantId:'t3', tenantName:'KOBEPay Technologies' },
    { id:'u5', propertyId:'p3', number:'Shop-08', type:'Retail', beds:0, baths:1, sqft:450, rent:3_000_000, status:'Occupied', tenantId:'t4', tenantName:'Bongo Foods Ltd' },
  ];
  const tenants: Tenant[] = [
    { id:'t1', name:'James Mwakasege', phone:'+255 712 345 678', email:'james@example.com', propertyId:'p1', unitId:'u1', unit:'A-12', leaseStart:`${y}-01-01`, leaseEnd:`${y}-12-31`, monthlyRent:2_500_000, status:'Active', shortCode:'KBE0001', paid:25_000_000, balance:5_000_000 },
    { id:'t2', name:'Grace Mwangala', phone:'+255 713 456 789', email:'grace@example.com', propertyId:'p1', unitId:'u2', unit:'B-05', leaseStart:`${y}-02-01`, leaseEnd:`${y+1}-01-31`, monthlyRent:1_800_000, status:'Active', shortCode:'KBE0002', paid:18_000_000, balance:3_600_000 },
    { id:'t3', name:'KOBEPay Technologies', phone:'+255 714 567 890', email:'admin@kobepay.co.tz', propertyId:'p2', unitId:'u4', unit:'Suite-301', leaseStart:`${y}-01-01`, leaseEnd:`${y+1}-12-31`, monthlyRent:6_000_000, status:'Active', shortCode:'KBE0003', paid:66_000_000, balance:6_000_000 },
    { id:'t4', name:'Bongo Foods Ltd', phone:'+255 717 890 123', email:'accounts@example.com', propertyId:'p3', unitId:'u5', unit:'Shop-08', leaseStart:`${y}-05-01`, leaseEnd:`${y+1}-04-30`, monthlyRent:3_000_000, status:'Late', shortCode:'KBE0004', paid:30_000_000, balance:6_000_000 },
  ];
  const leases: Lease[] = tenants.map((t) => ({ id:`l-${t.id}`, tenantId:t.id, unitId:t.unitId, start:t.leaseStart, end:t.leaseEnd, rent:t.monthlyRent, deposit:t.monthlyRent, dueDay:1, lateFee:Math.round(t.monthlyRent * 0.03), status:'Active' }));
  const charges: Charge[] = tenants.map((t) => ({ id:`c-${t.id}`, tenantId:t.id, unitId:t.unitId, period:nowPeriod, due:`${nowPeriod}-01`, amount:t.monthlyRent, paid:t.status === 'Late' ? 0 : t.monthlyRent, status:t.status === 'Late' ? 'Overdue' : 'Paid' }));
  const vendors: Vendor[] = [{ id:'v1', name:'Hill Country Plumbing', category:'Plumber', phone:'+255 755 111 222', email:'plumbing@example.com' }, { id:'v2', name:'Bright Spark Electric', category:'Electrician', phone:'+255 755 333 444', email:'electric@example.com' }];
  const workOrders: WorkOrder[] = [{ id:'wo1', propertyId:'p1', unitId:'u1', tenantId:'t1', vendorId:'v1', title:'Kitchen sink leak', priority:'Late', status:'Assigned', cost:120_000 }, { id:'wo2', propertyId:'p2', unitId:'u4', vendorId:'v2', title:'Generator inspection', priority:'Open', status:'Open', cost:250_000 }];
  return { properties, units, tenants, leases, charges, vendors, workOrders, payments: [] as Payment[] };
})();

export default function OpenPropertyApp() {
  const [tab, setTab] = useState<Tab>('dashboard');
  const [search, setSearch] = useState('');
  const [period, setPeriod] = useState(nowPeriod);
  const [data, setData] = useState(demo);
  const [sync, setSync] = useState('Open Property UI port loaded. Existing KobeOS property API syncs properties, units, tenants and payments.');
  const [loading, setLoading] = useState(false);
  const [payTenant, setPayTenant] = useState<Tenant | null>(null);
  const [payAmount, setPayAmount] = useState('');
  const [payRef, setPayRef] = useState('');

  async function refresh() {
    setLoading(true);
    try {
      await ensureSession();
      const [ps, us, ts, pays] = await Promise.all([api<ApiProperty[]>('/property/properties'), api<ApiUnit[]>('/property/units'), api<ApiTenant[]>('/property/tenants'), api<ApiPayment[]>('/property/payments')]);
      if (!ps.length && !us.length && !ts.length) { setSync('Backend reachable but property data is empty, using demo portfolio.'); return; }
      const units = us.map<Unit>((u) => ({ id:u.id, propertyId:u.propertyId, number:u.unitNumber, type:'Unit', beds:0, baths:1, sqft:0, rent:Number(u.rentAmount || 0), status:u.status === 'occupied' ? 'Occupied' : 'Vacant' }));
      const tenants = ts.map<Tenant>((t) => { const unit = units.find((u) => u.id === t.unitId); const paid = pays.filter((p) => p.tenantId === t.id).reduce((s,p) => s + Number(p.amount || 0), 0); const yearly = (unit?.rent || 0) * 12; return { id:t.id, name:t.name, phone:t.phone, email:t.email || '', propertyId:unit?.propertyId || '', unitId:unit?.id || '', unit:unit?.number || '', leaseStart:t.leaseStart || '', leaseEnd:t.leaseEnd || '', monthlyRent:unit?.rent || 0, status:t.status === 'pending' ? 'Pending' : t.status === 'past' ? 'Late' : 'Active', shortCode:`KBE${t.id.replace(/-/g,'').slice(0,6).toUpperCase()}`, paid, balance:Math.max(yearly - paid, 0) }; });
      const properties = ps.map<Property>((p, i) => { const propUnits = units.filter((u) => u.propertyId === p.id); return { id:p.id, name:p.name, type:p.type, address:p.address, units:p.totalUnits || propUnits.length, occupied:propUnits.filter((u) => u.status === 'Occupied').length, monthlyIncome:propUnits.reduce((s,u) => s + u.rent, 0), color:['blue','emerald','amber'][i % 3] }; });
      setData((old) => ({ ...old, properties, units, tenants, leases: tenants.map((t) => ({ id:`l-${t.id}`, tenantId:t.id, unitId:t.unitId, start:t.leaseStart, end:t.leaseEnd, rent:t.monthlyRent, deposit:t.monthlyRent, dueDay:1, lateFee:Math.round(t.monthlyRent * 0.03), status:'Active' })), payments:pays.map((p) => ({ id:p.id, tenantId:p.tenantId, unitId:p.unitId, amount:Number(p.amount || 0), paidAt:p.paidAt, method:p.method, reference:p.reference || '' })) }));
      setSync('Synced with KobeOS backend.');
    } catch (e) { setSync(`Offline/demo mode: ${(e as Error).message}`); }
    finally { setLoading(false); }
  }

  useEffect(() => { void refresh(); }, []);

  const stats = useMemo(() => { const occupied = data.units.filter((u) => u.status === 'Occupied').length; const charged = data.charges.reduce((s,c) => s + c.amount, 0); const paid = data.charges.reduce((s,c) => s + c.paid, 0); return { occupied, units:data.units.length, occupancy: data.units.length ? Math.round(occupied / data.units.length * 100) : 0, leases:data.leases.length, outstanding:charged - paid, openOrders:data.workOrders.filter((w) => w.status !== 'Completed').length }; }, [data]);
  function openPayment(t: Tenant, amount = t.balance || t.monthlyRent) { setPayTenant(t); setPayAmount(String(amount)); setPayRef(`RCP-${Date.now().toString().slice(-6)}`); }
  async function savePayment() { if (!payTenant) return; const amount = Number(payAmount); setLoading(true); try { await api('/property/payments', { method:'POST', body:JSON.stringify({ tenantId:payTenant.id, unitId:payTenant.unitId, amount, currency:'TZS', forMonth:`${period}-01`, paidAt:new Date().toISOString(), method:'Cash', reference:payRef }) }); setSync('Payment recorded in KobeOS backend.'); } catch (e) { setSync(`Payment queued/offline: ${(e as Error).message}`); } setData((old) => ({ ...old, tenants: old.tenants.map((t) => t.id === payTenant.id ? { ...t, paid:t.paid + amount, balance:Math.max(t.balance - amount, 0), status:Math.max(t.balance - amount, 0) ? t.status : 'Active' } : t) })); setPayTenant(null); setLoading(false); }
  const nav = [['dashboard','Dashboard',BarChart3], ['properties','Properties',Building2], ['units','Units',DoorOpen], ['tenants','Tenants',Users], ['leases','Leases',FileText], ['rent','Rent Ledger',Receipt], ['maintenance','Maintenance',Wrench], ['vendors','Vendors',UserCheck], ['settings','Policy',Settings]] as const;

  return <div className="flex h-full min-h-0 bg-[#080b12] text-white"><aside className="hidden w-60 shrink-0 border-r border-white/10 bg-[#0d111b] p-3 md:block"><div className="mb-4 rounded-2xl border border-white/10 bg-white/[0.03] p-3"><div className="text-sm font-semibold">Open Property</div><div className="text-[11px] text-white/40">KobeOS port</div></div><div className="space-y-1">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex w-full items-center gap-2 rounded-xl px-3 py-2 text-xs ${tab === key ? 'bg-blue-500/15 text-blue-300' : 'text-white/55 hover:bg-white/[0.04]'}`}><Icon className="h-4 w-4" />{label}</button>)}</div><div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-3 text-[11px] text-white/45">{sync}</div></aside><main className="flex min-w-0 flex-1 flex-col"><header className="border-b border-white/10 bg-[#0b0f18] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-semibold">Property Management</div><div className="text-[11px] text-white/40">Dashboard, leases, rent ledger, maintenance, vendors and policy</div></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-white/30" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="h-9 w-72 rounded-xl border-white/10 bg-white/[0.04] pl-9 text-xs text-white" placeholder="Search..." /></div><Button onClick={refresh} disabled={loading} className="h-9 rounded-xl bg-blue-500 text-xs">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}</Button></div></div><div className="mt-3 flex gap-1 overflow-x-auto md:hidden">{nav.map(([key,label,Icon]) => <button key={key} onClick={() => setTab(key)} className={`shrink-0 rounded-lg border px-2 py-1 text-[10px] ${tab===key?'border-blue-500/30 bg-blue-500/15 text-blue-300':'border-white/10 text-white/50'}`}><Icon className="mr-1 inline h-3 w-3" />{label}</button>)}</div></header><ScrollArea className="flex-1"><div className="p-4">{tab === 'dashboard' && <Dashboard stats={stats} data={data} setTab={setTab} openPayment={openPayment} />}{tab === 'properties' && <Properties data={data} q={search} />}{tab === 'units' && <Units data={data} q={search} />}{tab === 'tenants' && <Tenants data={data} q={search} openPayment={openPayment} />}{tab === 'leases' && <Leases data={data} />}{tab === 'rent' && <Rent data={data} period={period} setPeriod={setPeriod} openPayment={openPayment} />}{tab === 'maintenance' && <Maintenance data={data} />}{tab === 'vendors' && <Vendors data={data} />}{tab === 'settings' && <Policy />}</div></ScrollArea></main>{payTenant && <PaymentModal tenant={payTenant} amount={payAmount} setAmount={setPayAmount} reference={payRef} setReference={setPayRef} close={() => setPayTenant(null)} save={savePayment} loading={loading} />}</div>;
}

function Dashboard({ stats, data, setTab, openPayment }: { stats: any; data: typeof demo; setTab: (t: Tab) => void; openPayment: (t: Tenant) => void }) { return <div className="space-y-4"><Title title="Portfolio Dashboard" sub="At-a-glance KPIs, this month rent, open work orders and lease expirations." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Occupancy" value={`${stats.occupancy}%`} sub={`${stats.occupied}/${stats.units} units`} /><Metric label="Active Leases" value={stats.leases} sub="current contracts" /><Metric label="Outstanding" value={money(stats.outstanding)} sub="this month" /><Metric label="Open Work Orders" value={stats.openOrders} sub="maintenance" /></div><div className="grid gap-4 xl:grid-cols-2"><Panel title="Overdue / Due Tenants">{data.tenants.filter(t=>t.balance>0).map(t=><Row key={t.id} left={<Person t={t}/>} mid={money(t.balance)} right={<Button onClick={()=>openPayment(t)} className="h-8 bg-emerald-500/15 text-emerald-300">Record</Button>} />)}</Panel><Panel title="Open Work Orders">{data.workOrders.map(w=><Row key={w.id} left={<div><div className="font-medium">{w.title}</div><div className="text-xs text-white/40">{prop(data,w.propertyId)}</div></div>} mid={<Badge s={w.priority}/>} right={<Badge s={w.status}/>} />)}</Panel></div><Button onClick={() => setTab('rent')} className="rounded-xl bg-blue-500">Open Rent Ledger</Button></div> }
function Properties({data,q}:{data:typeof demo;q:string}){const rows=data.properties.filter(p=>`${p.name} ${p.address}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-3"><Title title="Properties" sub="Property cards with type, address, color tag and occupancy snapshot." action="Add Property"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(p=><Card key={p.id} className="border-white/10 bg-white/[0.03]"><CardContent className="p-4"><div className="flex items-start justify-between"><div><div className="font-semibold">{p.name}</div><div className="text-xs text-white/40">{p.type}</div></div><Badge s="Active"/></div><div className="mt-3 flex items-center gap-1 text-xs text-white/45"><MapPin className="h-3 w-3"/>{p.address}</div><div className="mt-3 grid grid-cols-3 gap-2"><Mini k="Units" v={p.units}/><Mini k="Occupied" v={p.occupied}/><Mini k="Monthly" v={money(p.monthlyIncome)}/></div></CardContent></Card>)}</div></div>}
function Units({data,q}:{data:typeof demo;q:string}){const rows=data.units.filter(u=>`${u.number} ${u.tenantName||''}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-3"><Title title="Units" sub="Bedrooms, bathrooms, square footage, market rent and status." action="Add Unit"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(u=><Card key={u.id} className="border-white/10 bg-white/[0.03]"><CardContent className="p-4"><div className="flex justify-between"><div><div className="font-semibold">{u.number}</div><div className="text-xs text-white/40">{prop(data,u.propertyId)}</div></div><Badge s={u.status}/></div><div className="mt-3 grid grid-cols-4 gap-2"><Mini k="Beds" v={u.beds}/><Mini k="Baths" v={u.baths}/><Mini k="Sqft" v={u.sqft||'—'}/><Mini k="Rent" v={money(u.rent)}/></div><div className="mt-3 text-xs text-white/45">{u.tenantName||'Vacant'}</div></CardContent></Card>)}</div></div>}
function Tenants({data,q,openPayment}:{data:typeof demo;q:string;openPayment:(t:Tenant)=>void}){const rows=data.tenants.filter(t=>`${t.name} ${t.phone} ${t.unit}`.toLowerCase().includes(q.toLowerCase()));return <div className="space-y-3"><Title title="Tenants" sub="Searchable tenant list with active unit, contact info, employer, income and emergency contact." action="Add Tenant"/><Table heads={['Tenant','Unit','Lease','Balance','Status','Action']}>{rows.map(t=><tr key={t.id}><td><Person t={t}/></td><td>{prop(data,t.propertyId)} · {t.unit}</td><td>{t.leaseStart} → {t.leaseEnd}</td><td className="text-right text-amber-300">{money(t.balance)}</td><td><Badge s={t.status}/></td><td className="text-right"><Button onClick={()=>openPayment(t)} className="h-8 bg-emerald-500/15 text-emerald-300"><CreditCard className="mr-1 h-3 w-3"/>Pay</Button></td></tr>)}</Table></div>}
function Leases({data}:{data:typeof demo}){return <div className="space-y-3"><Title title="Leases" sub="One row per lease with tenant, property/unit, term, monthly rent, deposit, due day and late fee." action="Add Lease"/><Table heads={['Tenant','Unit','Term','Rent','Deposit','Status']}>{data.leases.map(l=>{const t=data.tenants.find(x=>x.id===l.tenantId);const u=data.units.find(x=>x.id===l.unitId);return <tr key={l.id}><td>{t?.name}</td><td>{u?.number}</td><td>{l.start} → {l.end}</td><td>{money(l.rent)}</td><td>{money(l.deposit)}</td><td><Badge s={l.status}/></td></tr>})}</Table></div>}
function Rent({data,period,setPeriod,openPayment}:{data:typeof demo;period:string;setPeriod:(p:string)=>void;openPayment:(t:Tenant,a?:number)=>void}){const totals=data.charges.reduce((a,c)=>({charged:a.charged+c.amount,paid:a.paid+c.paid}),{charged:0,paid:0});return <div className="space-y-3"><div className="flex items-center justify-between"><Title title="Rent Ledger" sub="Period navigator, monthly charges, payment recording and auto status updates."/><div className="flex items-center gap-1 rounded-xl border border-white/10 p-1"><button onClick={()=>setPeriod(shiftPeriod(period,-1))}><ChevronLeft className="h-4 w-4"/></button><span className="px-3 text-xs">{periodName(period)}</span><button onClick={()=>setPeriod(shiftPeriod(period,1))}><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid gap-3 sm:grid-cols-3"><Metric label="Charged" value={money(totals.charged)} sub="period total"/><Metric label="Collected" value={money(totals.paid)} sub="received"/><Metric label="Outstanding" value={money(totals.charged-totals.paid)} sub="balance"/></div><Table heads={['Tenant','Unit','Due','Charge','Paid','Status','Action']}>{data.charges.map(c=>{const t=data.tenants.find(x=>x.id===c.tenantId);const u=data.units.find(x=>x.id===c.unitId);const due=c.amount-c.paid;return <tr key={c.id}><td>{t?.name}</td><td>{u?.number}</td><td>{c.due}</td><td>{money(c.amount)}</td><td>{money(c.paid)}</td><td><Badge s={c.status}/></td><td>{t&&due>0?<Button onClick={()=>openPayment(t,due)} className="h-8 bg-emerald-500/15 text-emerald-300">Record</Button>:null}</td></tr>})}</Table></div>}
function Maintenance({data}:{data:typeof demo}){return <div className="space-y-3"><Title title="Maintenance" sub="Work orders with priority, status, property, unit, vendor and cost." action="New Work Order"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.workOrders.map(w=><Card key={w.id} className="border-white/10 bg-white/[0.03]"><CardContent className="p-4"><div className="flex justify-between"><div><div className="font-semibold">{w.title}</div><div className="text-xs text-white/40">{prop(data,w.propertyId)}</div></div><Badge s={w.priority}/></div><div className="mt-3 flex items-center justify-between"><Badge s={w.status}/><span className="text-xs text-white/45">{money(w.cost)}</span></div></CardContent></Card>)}</div></div>}
function Vendors({data}:{data:typeof demo}){return <div className="space-y-3"><Title title="Vendors" sub="Vendor directory by category: plumber, electrician, HVAC, handyman, cleaning, landscaping and general." action="Add Vendor"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.vendors.map(v=><Card key={v.id} className="border-white/10 bg-white/[0.03]"><CardContent className="p-4"><div className="font-semibold">{v.name}</div><div className="text-xs text-blue-300">{v.category}</div><div className="mt-3 space-y-1 text-xs text-white/45"><div><Phone className="mr-1 inline h-3 w-3"/>{v.phone}</div><div><Mail className="mr-1 inline h-3 w-3"/>{v.email}</div></div></CardContent></Card>)}</div></div>}
function Policy(){const gaps=[['Backend leases API','Missing'],['Rent charge generation endpoint','Missing'],['Vendor/work-order persistence','Missing'],['Tenant/owner portal','Future'],['KobePay online payment callbacks','Future']];return <div className="grid gap-4 xl:grid-cols-2"><Panel title="Rent Policy Defaults"><div className="grid gap-3"><Input defaultValue="1" className="border-white/10 bg-white/[0.04]"/><Input defaultValue="50000" className="border-white/10 bg-white/[0.04]"/><Input defaultValue="5" className="border-white/10 bg-white/[0.04]"/><Input defaultValue="TZS" className="border-white/10 bg-white/[0.04]"/></div></Panel><Panel title="Missing Features to Add Next">{gaps.map(([a,b])=><Row key={a} left={a} right={<Badge s={b as Status}/>}/>)}</Panel></div>}
function PaymentModal({tenant,amount,setAmount,reference,setReference,close,save,loading}:{tenant:Tenant;amount:string;setAmount:(v:string)=>void;reference:string;setReference:(v:string)=>void;close:()=>void;save:()=>void;loading:boolean}){const qr=JSON.stringify({app:'KobeOS Property',tenant:tenant.shortCode,amount:Number(amount)});return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#0d111b] p-4"><div className="mb-4 flex justify-between"><div><div className="font-semibold">Record Payment</div><div className="text-xs text-white/40">{tenant.name} · {tenant.unit}</div></div><button onClick={close}><X className="h-4 w-4"/></button></div><div className="grid gap-4 sm:grid-cols-[150px_1fr]"><div className="rounded-xl bg-white p-3"><QRCodeSVG value={qr} size={120}/></div><div className="space-y-3"><Input value={amount} onChange={e=>setAmount(e.target.value)} type="number" className="border-white/10 bg-white/[0.04]"/><Input value={reference} onChange={e=>setReference(e.target.value)} className="border-white/10 bg-white/[0.04]"/><Button onClick={save} disabled={loading} className="w-full bg-emerald-500">{loading?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<CheckCircle2 className="mr-2 h-4 w-4"/>}Save Payment</Button></div></div></div></div>}
function Title({title,sub,action}:{title:string;sub:string;action?:string}){return <div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">{title}</h2><p className="text-xs text-white/40">{sub}</p></div>{action&&<Button className="bg-blue-500"><Plus className="mr-1 h-3 w-3"/>{action}</Button>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <Card className="border-white/10 bg-white/[0.03]"><CardHeader><CardTitle className="text-sm">{title}</CardTitle></CardHeader><CardContent className="space-y-2">{children}</CardContent></Card>}
function Metric({label,value,sub}:{label:string;value:React.ReactNode;sub:string}){return <Card className="border-white/10 bg-white/[0.03]"><CardContent className="p-4"><div className="text-[11px] uppercase text-white/35">{label}</div><div className="mt-1 text-xl font-bold">{value}</div><div className="text-xs text-white/40">{sub}</div></CardContent></Card>}
function Mini({k,v}:{k:string;v:React.ReactNode}){return <div className="rounded-lg bg-white/[0.04] p-2"><div className="text-[9px] uppercase text-white/30">{k}</div><div className="truncate text-xs font-semibold">{v}</div></div>}
function Badge({s}:{s:Status|string}){const c=String(s).includes('Overdue')||String(s).includes('Missing')||String(s).includes('Late')?'bg-red-500/10 text-red-300 border-red-500/20':String(s).includes('Paid')||String(s).includes('Active')||String(s).includes('Completed')?'bg-emerald-500/10 text-emerald-300 border-emerald-500/20':'bg-blue-500/10 text-blue-300 border-blue-500/20';return <span className={`inline-flex rounded-full border px-2 py-0.5 text-[10px] font-semibold ${c}`}>{s}</span>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><table className="w-full text-sm"><thead className="bg-white/[0.03] text-left text-[10px] uppercase text-white/35"><tr>{heads.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-white/10 [&_td]:p-3 [&_td]:text-xs [&_td]:text-white/65">{children}</tbody></table></div>}
function Row({left,mid,right}:{left:React.ReactNode;mid?:React.ReactNode;right?:React.ReactNode}){return <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] p-2"><div>{left}</div>{mid&&<div className="text-xs text-white/60">{mid}</div>}{right&&<div>{right}</div>}</div>}
function Person({t}:{t:Tenant}){return <div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-500/15 text-xs font-bold text-blue-200">{initials(t.name)}</div><div><div className="font-medium text-white/90">{t.name}</div><div className="text-[11px] text-white/40">{t.phone} · {t.shortCode}</div></div></div>}
function prop(data:typeof demo,id?:string){return data.properties.find(p=>p.id===id)?.name||'No property'}
