import type { KobeCatalogue } from './kobe-models.types';

/**
 * Static catalogue embedded in the server.
 * In production this is fetched from KOBE_MODELS_CDN_URL/catalogue.json
 * and cached; this file serves as the offline fallback.
 */
export const EMBEDDED_CATALOGUE: KobeCatalogue = {
  version: '1.0.0',
  updatedAt: '2026-05-16',
  models: [
    // ── Chat ──────────────────────────────────────────────────────────────────
    {
      id: 'mistral:7b',
      name: 'Kobe-Mistral 7B',
      description: 'Fast, capable chat model. Best balance of speed and quality for most tasks.',
      category: 'chat',
      sizeBytes: 4_100_000_000,
      sizeLabel: '4.1 GB',
      minVramGb: 6,
      kobeOptimised: true,
      downloadUrl: 'https://models.kobe/chat/kobe-mistral-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-mistral-7b',
      ollamaFallback: 'mistral:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/mistralai/Mistral-7B-v0.1',
      version: '0.1',
      recommended: true,
      tags: ['chat', 'fast', 'general'],
    },
    {
      id: 'llama3.2:3b',
      name: 'Llama 3.2 3B',
      description: 'Lightweight Llama model. Runs on CPU, ideal for low-resource devices.',
      category: 'chat',
      sizeBytes: 2_000_000_000,
      sizeLabel: '2.0 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/llama3.2-3b-q4.kobemodel',
      checksum: 'placeholder-sha256-llama3-3b',
      ollamaFallback: 'llama3.2:3b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/meta-llama/Llama-3.2-3B',
      version: '3.2',
      recommended: true,
      tags: ['chat', 'cpu', 'lightweight'],
    },
    {
      id: 'llama3.1:8b',
      name: 'Llama 3.1 8B',
      description: 'Strong general-purpose model with good instruction following.',
      category: 'chat',
      sizeBytes: 4_700_000_000,
      sizeLabel: '4.7 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/llama3.1-8b-q4.kobemodel',
      checksum: 'placeholder-sha256-llama3-8b',
      ollamaFallback: 'llama3.1:8b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/meta-llama/Meta-Llama-3.1-8B',
      version: '3.1',
      recommended: false,
      tags: ['chat', 'general'],
    },
    {
      id: 'gemma2:2b',
      name: 'Gemma 2 2B',
      description: 'Google\'s compact model. Excellent for on-device inference.',
      category: 'chat',
      sizeBytes: 1_600_000_000,
      sizeLabel: '1.6 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/gemma2-2b-q4.kobemodel',
      checksum: 'placeholder-sha256-gemma2-2b',
      ollamaFallback: 'gemma2:2b',
      license: 'gemma',
      upstreamUrl: 'https://huggingface.co/google/gemma-2-2b',
      version: '2.0',
      recommended: true,
      tags: ['chat', 'cpu', 'google'],
    },
    {
      id: 'phi4:14b',
      name: 'Phi-4 14B',
      description: 'Microsoft\'s reasoning-focused model. Strong at math and logic.',
      category: 'chat',
      sizeBytes: 8_500_000_000,
      sizeLabel: '8.5 GB',
      minVramGb: 10,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/phi4-14b-q4.kobemodel',
      checksum: 'placeholder-sha256-phi4-14b',
      ollamaFallback: 'phi4:14b',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/microsoft/phi-4',
      version: '4.0',
      recommended: false,
      tags: ['chat', 'reasoning', 'math'],
    },
    {
      id: 'qwen2.5:7b',
      name: 'Qwen 2.5 7B',
      description: 'Alibaba\'s multilingual model. Strong CJK and Arabic support.',
      category: 'chat',
      sizeBytes: 4_400_000_000,
      sizeLabel: '4.4 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/qwen2.5-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-qwen2-7b',
      ollamaFallback: 'qwen2.5:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/Qwen/Qwen2.5-7B',
      version: '2.5',
      recommended: false,
      tags: ['chat', 'multilingual'],
    },
    // ── Coding ────────────────────────────────────────────────────────────────
    {
      id: 'deepseek-coder-v2:16b',
      name: 'Kobe-DeepSeek Coder V2 16B',
      description: 'Best-in-class open coding model. Supports 338 languages.',
      category: 'coding',
      sizeBytes: 9_000_000_000,
      sizeLabel: '9.0 GB',
      minVramGb: 12,
      kobeOptimised: true,
      downloadUrl: 'https://models.kobe/coding/kobe-deepseek-coder-v2-16b-q4.kobemodel',
      checksum: 'placeholder-sha256-deepseek-coder-v2',
      ollamaFallback: 'deepseek-coder-v2:16b',
      license: 'other',
      upstreamUrl: 'https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct',
      version: '2.0',
      recommended: true,
      tags: ['coding', 'completion', 'chat'],
    },
    {
      id: 'codellama:7b',
      name: 'CodeLlama 7B',
      description: 'Meta\'s code-focused Llama variant. Good for completion tasks.',
      category: 'coding',
      sizeBytes: 3_800_000_000,
      sizeLabel: '3.8 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/coding/codellama-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-codellama-7b',
      ollamaFallback: 'codellama:7b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/codellama/CodeLlama-7b-hf',
      version: '1.0',
      recommended: false,
      tags: ['coding', 'completion'],
    },
    // ── Vision ────────────────────────────────────────────────────────────────
    {
      id: 'llava:7b',
      name: 'LLaVA 7B',
      description: 'Vision-language model. Analyse images, screenshots, and diagrams.',
      category: 'vision',
      sizeBytes: 4_500_000_000,
      sizeLabel: '4.5 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/vision/llava-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-llava-7b',
      ollamaFallback: 'llava:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/liuhaotian/llava-v1.5-7b',
      version: '1.5',
      recommended: true,
      tags: ['vision', 'multimodal'],
    },
    // ── Sports ────────────────────────────────────────────────────────────────
    {
      id: 'kobe-football-vision:1b',
      name: 'Kobe Football Vision',
      description: 'YOLO-based player tracking and event detection fine-tuned on football footage.',
      category: 'sports',
      sizeBytes: 600_000_000,
      sizeLabel: '600 MB',
      minVramGb: 2,
      kobeOptimised: true,
      downloadUrl: 'https://models.kobe/sports/kobe-football-vision-1b.kobemodel',
      checksum: 'placeholder-sha256-kobe-football-vision',
      license: 'apache-2.0',
      upstreamUrl: 'https://github.com/ultralytics/ultralytics',
      version: '1.0',
      recommended: true,
      tags: ['sports', 'football', 'tracking', 'yolo'],
    },
    // ── Embedding ─────────────────────────────────────────────────────────────
    {
      id: 'nomic-embed-text:latest',
      name: 'Nomic Embed Text',
      description: 'High-quality text embeddings for RAG and semantic search.',
      category: 'embedding',
      sizeBytes: 274_000_000,
      sizeLabel: '274 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/embedding/nomic-embed-text.kobemodel',
      checksum: 'placeholder-sha256-nomic-embed',
      ollamaFallback: 'nomic-embed-text:latest',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/nomic-ai/nomic-embed-text-v1',
      version: '1.0',
      recommended: true,
      tags: ['embedding', 'rag', 'search'],
    },
  ],
};
