import type { KobeCatalogue } from './kobe-models.types';

/**
 * Static catalogue embedded in the server.
 * In production this is fetched from KOBE_MODELS_CDN_URL/catalogue.json
 * and cached; this file serves as the offline fallback.
 */
export const EMBEDDED_CATALOGUE: KobeCatalogue = {
  version: '1.0.0',
  updatedAt: '2026-05-22',
  models: [
    // ── Chat ──────────────────────────────────────────────────────────────────
    {
      id: 'mistral:7b',
      name: 'Kobe-Mistral 7B',
      description: 'Fast, capable chat model. Best balance of speed and quality for most tasks.',
      category: 'chat',
      sizeBytes: 4_100_000_000,
      sizeLabel: '4.1 GB',
      minVramGb: 6,
      kobeOptimised: true,
      downloadUrl: 'https://models.kobe/chat/kobe-mistral-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-mistral-7b',
      ollamaFallback: 'mistral:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/mistralai/Mistral-7B-v0.1',
      version: '0.1',
      recommended: true,
      tags: ['chat', 'fast', 'general'],
    },
    {
      id: 'llama3.2:3b',
      name: 'Llama 3.2 3B',
      description: 'Lightweight Llama model. Runs on CPU, ideal for low-resource devices.',
      category: 'chat',
      sizeBytes: 2_000_000_000,
      sizeLabel: '2.0 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/llama3.2-3b-q4.kobemodel',
      checksum: 'placeholder-sha256-llama3-3b',
      ollamaFallback: 'llama3.2:3b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/meta-llama/Llama-3.2-3B',
      version: '3.2',
      recommended: true,
      tags: ['chat', 'cpu', 'lightweight'],
    },
    {
      id: 'llama3.1:8b',
      name: 'Llama 3.1 8B',
      description: 'Strong general-purpose model with good instruction following.',
      category: 'chat',
      sizeBytes: 4_700_000_000,
      sizeLabel: '4.7 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/llama3.1-8b-q4.kobemodel',
      checksum: 'placeholder-sha256-llama3-8b',
      ollamaFallback: 'llama3.1:8b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/meta-llama/Meta-Llama-3.1-8B',
      version: '3.1',
      recommended: false,
      tags: ['chat', 'general'],
    },
    {
      id: 'gemma2:2b',
      name: 'Gemma 2 2B',
      description: 'Google\'s compact model. Excellent for on-device inference.',
      category: 'chat',
      sizeBytes: 1_600_000_000,
      sizeLabel: '1.6 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/gemma2-2b-q4.kobemodel',
      checksum: 'placeholder-sha256-gemma2-2b',
      ollamaFallback: 'gemma2:2b',
      license: 'gemma',
      upstreamUrl: 'https://huggingface.co/google/gemma-2-2b',
      version: '2.0',
      recommended: true,
      tags: ['chat', 'cpu', 'google'],
    },
    {
      id: 'phi4:14b',
      name: 'Phi-4 14B',
      description: 'Microsoft\'s reasoning-focused model. Strong at math and logic.',
      category: 'chat',
      sizeBytes: 8_500_000_000,
      sizeLabel: '8.5 GB',
      minVramGb: 10,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/phi4-14b-q4.kobemodel',
      checksum: 'placeholder-sha256-phi4-14b',
      ollamaFallback: 'phi4:14b',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/microsoft/phi-4',
      version: '4.0',
      recommended: false,
      tags: ['chat', 'reasoning', 'math'],
    },
    {
      id: 'qwen2.5:7b',
      name: 'Qwen 2.5 7B',
      description: 'Alibaba\'s multilingual model. Strong CJK and Arabic support.',
      category: 'chat',
      sizeBytes: 4_400_000_000,
      sizeLabel: '4.4 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/qwen2.5-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-qwen2-7b',
      ollamaFallback: 'qwen2.5:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/Qwen/Qwen2.5-7B',
      version: '2.5',
      recommended: false,
      tags: ['chat', 'multilingual'],
    },
    {
      id: 'deepseek-r1:8b',
      name: 'DeepSeek-R1 8B',
      description: 'Reasoning model with chain-of-thought. Default chat model for KobeOS. Strong at analysis, planning, and structured tasks.',
      category: 'chat',
      sizeBytes: 4_900_000_000,
      sizeLabel: '4.9 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/chat/deepseek-r1-8b-q4.kobemodel',
      checksum: 'placeholder-sha256-deepseek-r1-8b',
      ollamaFallback: 'deepseek-r1:8b',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
      version: 'r1',
      recommended: true,
      tags: ['chat', 'reasoning', 'default'],
    },
    // ── Coding ────────────────────────────────────────────────────────────────
    {
      id: 'deepseek-coder-v2:16b',
      name: 'Kobe-DeepSeek Coder V2 16B',
      description: 'Best-in-class open coding model. Supports 338 languages.',
      category: 'coding',
      sizeBytes: 9_000_000_000,
      sizeLabel: '9.0 GB',
      minVramGb: 12,
      kobeOptimised: true,
      downloadUrl: 'https://models.kobe/coding/kobe-deepseek-coder-v2-16b-q4.kobemodel',
      checksum: 'placeholder-sha256-deepseek-coder-v2',
      ollamaFallback: 'deepseek-coder-v2:16b',
      license: 'other',
      upstreamUrl: 'https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct',
      version: '2.0',
      recommended: true,
      tags: ['coding', 'completion', 'chat'],
    },
    {
      id: 'codellama:7b',
      name: 'CodeLlama 7B',
      description: 'Meta\'s code-focused Llama variant. Good for completion tasks.',
      category: 'coding',
      sizeBytes: 3_800_000_000,
      sizeLabel: '3.8 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/coding/codellama-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-codellama-7b',
      ollamaFallback: 'codellama:7b',
      license: 'llama',
      upstreamUrl: 'https://huggingface.co/codellama/CodeLlama-7b-hf',
      version: '1.0',
      recommended: false,
      tags: ['coding', 'completion'],
    },
    // ── Vision ────────────────────────────────────────────────────────────────
    {
      id: 'llava:7b',
      name: 'LLaVA 7B',
      description: 'Vision-language model. Analyse images, screenshots, and diagrams.',
      category: 'vision',
      sizeBytes: 4_500_000_000,
      sizeLabel: '4.5 GB',
      minVramGb: 6,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/vision/llava-7b-q4.kobemodel',
      checksum: 'placeholder-sha256-llava-7b',
      ollamaFallback: 'llava:7b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/liuhaotian/llava-v1.5-7b',
      version: '1.5',
      recommended: true,
      tags: ['vision', 'multimodal'],
    },
    {
      id: 'moondream:1.8b',
      name: 'Moondream 1.8B',
      description: 'Compact vision model. Runs on CPU. Used as the fallback when LLaVA is unavailable.',
      category: 'vision',
      sizeBytes: 1_500_000_000,
      sizeLabel: '1.5 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/vision/moondream-1.8b-q4.kobemodel',
      checksum: 'placeholder-sha256-moondream-1.8b',
      ollamaFallback: 'moondream:1.8b',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/vikhyatk/moondream2',
      version: '2.0',
      recommended: true,
      tags: ['vision', 'multimodal', 'cpu', 'lightweight'],
    },
    // ── Sports ────────────────────────────────────────────────────────────────
    {
      id: 'kobe-football-vision:1b',
      name: 'Kobe Football Vision',
      description: 'YOLOv8n fine-tuned for football: player/ball/goalpost detection, home/away/referee classification, ByteTrack integration for player tracking.',
      category: 'sports',
      // Size will be updated after training + bundling.
      // Run: python scripts/build-football-vision.py --mode train
      //      python scripts/build-football-vision.py --mode export --weights runs/detect/kobe-football-vision/weights/best.pt
      //      npm run models:bundle -- --model kobe-football-vision:1b --weights runs/detect/kobe-football-vision/weights/best.pt
      sizeBytes: 12_000_000,   // ~12 MB for YOLOv8n — update after bundling
      sizeLabel: '~12 MB',
      minVramGb: 0,            // runs on CPU; GPU recommended for real-time
      kobeOptimised: true,
      // Set after running: npm run models:bundle && npm run models:upload
      downloadUrl: 'https://models.kobe/sports/kobe-football-vision-1b.kobemodel',
      // Set after bundling — printed by build-football-vision.py --mode export
      checksum: 'pending-run-build-football-vision-py',
      license: 'apache-2.0',
      upstreamUrl: 'https://github.com/ultralytics/ultralytics',
      version: '1.0',
      recommended: true,
      tags: ['sports', 'football', 'tracking', 'yolo', 'bytetrack'],
    },
    // ── Speech ────────────────────────────────────────────────────────────────
    {
      id: 'whisper:base',
      name: 'Whisper Base',
      description: 'OpenAI Whisper base model for offline speech-to-text. 74M params. Runs on CPU. Good accuracy for clear speech.',
      category: 'speech',
      sizeBytes: 148_000_000,
      sizeLabel: '148 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/speech/whisper-base.kobemodel',
      checksum: 'placeholder-sha256-whisper-base',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/openai/whisper-base',
      version: '20231117',
      recommended: true,
      tags: ['speech', 'stt', 'cpu', 'whisper'],
    },
    {
      id: 'whisper:small',
      name: 'Whisper Small',
      description: 'OpenAI Whisper small model. 244M params. Better accuracy than base, still CPU-capable. Recommended for noisy environments.',
      category: 'speech',
      sizeBytes: 488_000_000,
      sizeLabel: '488 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/speech/whisper-small.kobemodel',
      checksum: 'placeholder-sha256-whisper-small',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/openai/whisper-small',
      version: '20231117',
      recommended: false,
      tags: ['speech', 'stt', 'cpu', 'whisper'],
    },
    {
      id: 'whisper:medium',
      name: 'Whisper Medium',
      description: 'OpenAI Whisper medium model. 769M params. High accuracy, multilingual. Requires ~2 GB RAM.',
      category: 'speech',
      sizeBytes: 1_530_000_000,
      sizeLabel: '1.5 GB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/speech/whisper-medium.kobemodel',
      checksum: 'placeholder-sha256-whisper-medium',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/openai/whisper-medium',
      version: '20231117',
      recommended: false,
      tags: ['speech', 'stt', 'multilingual', 'whisper'],
    },
    // ── Speech (TTS — Piper) ──────────────────────────────────────────────────
    {
      id: 'piper:en_US-amy-medium',
      name: 'Piper · Amy (US English)',
      description: 'Offline neural text-to-speech via Piper. CPU-only, sub-second latency. Recommended starter voice for Kobe Studio voiceovers, Hotel notifications, accessibility readouts.',
      category: 'speech',
      sizeBytes: 63_000_000,
      sizeLabel: '63 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx',
      checksum: 'placeholder-sha256-piper-amy-medium',
      license: 'mit',
      upstreamUrl: 'https://github.com/rhasspy/piper',
      version: '1.0',
      recommended: true,
      tags: ['speech', 'tts', 'cpu', 'piper', 'en'],
    },
    {
      id: 'piper:en_GB-alba-medium',
      name: 'Piper · Alba (UK English)',
      description: 'UK English Piper voice. Good for storefront ads aimed at British / Commonwealth audiences.',
      category: 'speech',
      sizeBytes: 63_000_000,
      sizeLabel: '63 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alba/medium/en_GB-alba-medium.onnx',
      checksum: 'placeholder-sha256-piper-alba-medium',
      license: 'mit',
      upstreamUrl: 'https://github.com/rhasspy/piper',
      version: '1.0',
      recommended: false,
      tags: ['speech', 'tts', 'cpu', 'piper', 'en'],
    },
    {
      id: 'piper:en_US-libritts-high',
      name: 'Piper · LibriTTS (US English, high)',
      description: 'Higher-quality Piper voice trained on LibriTTS. ~2× the model size, cleaner intonation, slightly slower.',
      category: 'speech',
      sizeBytes: 120_000_000,
      sizeLabel: '120 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx',
      checksum: 'placeholder-sha256-piper-libritts-high',
      license: 'mit',
      upstreamUrl: 'https://github.com/rhasspy/piper',
      version: '1.0',
      recommended: false,
      tags: ['speech', 'tts', 'cpu', 'piper', 'en', 'high-quality'],
    },
    // ── Translation (NLLB-200) ────────────────────────────────────────────────
    {
      id: 'nllb-200-distilled-600M',
      name: 'NLLB-200 Distilled 600M',
      description: 'Meta\'s "No Language Left Behind" multilingual translation model. 200+ languages including Swahili, Amharic, Hausa, Yoruba, Zulu, Igbo, Somali, Lingala, Kinyarwanda. Runs offline via ONNX through @huggingface/transformers.',
      category: 'translation',
      sizeBytes: 600_000_000,
      sizeLabel: '600 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/Xenova/nllb-200-distilled-600M/resolve/main/onnx/encoder_model_quantized.onnx',
      checksum: 'placeholder-sha256-nllb-200',
      license: 'other',
      upstreamUrl: 'https://huggingface.co/Xenova/nllb-200-distilled-600M',
      version: '1.0',
      recommended: true,
      tags: ['translation', 'multilingual', 'swahili', 'cpu', 'nllb'],
    },
    // ── Image edit (u²-Net family) ────────────────────────────────────────────
    {
      id: 'rmbg-1.4',
      name: 'BRIA RMBG-1.4 (u²-Net)',
      description: 'Background removal model. u²-Net architecture trained on a large dataset by BRIA AI. Best out-of-the-box quality for product photos, ID-card cutouts, storefront hero images. Non-commercial community licence.',
      category: 'image',
      sizeBytes: 176_000_000,
      sizeLabel: '170 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/briaai/RMBG-1.4/resolve/main/onnx/model.onnx',
      checksum: 'placeholder-sha256-rmbg-1-4',
      license: 'other',
      upstreamUrl: 'https://huggingface.co/briaai/RMBG-1.4',
      version: '1.4',
      recommended: true,
      tags: ['image', 'background-removal', 'u2net', 'cpu'],
    },
    {
      id: 'u2net',
      name: 'u²-Net (original)',
      description: 'The original u²-Net background-removal model. Strict MIT licence — safe for commercial use. Slightly lower quality than RMBG-1.4 but fully permissive.',
      category: 'image',
      sizeBytes: 176_000_000,
      sizeLabel: '170 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://huggingface.co/Xenova/u2net/resolve/main/onnx/model.onnx',
      checksum: 'placeholder-sha256-u2net',
      license: 'mit',
      upstreamUrl: 'https://huggingface.co/Xenova/u2net',
      version: '1.0',
      recommended: false,
      tags: ['image', 'background-removal', 'u2net', 'cpu', 'mit'],
    },
    // ── Embedding ─────────────────────────────────────────────────────────────
    {
      id: 'nomic-embed-text:latest',
      name: 'Nomic Embed Text',
      description: 'High-quality text embeddings for RAG and semantic search.',
      category: 'embedding',
      sizeBytes: 274_000_000,
      sizeLabel: '274 MB',
      minVramGb: 0,
      kobeOptimised: false,
      downloadUrl: 'https://models.kobe/embedding/nomic-embed-text.kobemodel',
      checksum: 'placeholder-sha256-nomic-embed',
      ollamaFallback: 'nomic-embed-text:latest',
      license: 'apache-2.0',
      upstreamUrl: 'https://huggingface.co/nomic-ai/nomic-embed-text-v1',
      version: '1.0',
      recommended: true,
      tags: ['embedding', 'rag', 'search'],
    },
  ],
};
